/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_valores (XDR *xdrs, valores *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->i))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->j))
		 return FALSE;
	return TRUE;
}
