/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct valores {
	float i;
	float j;
};
typedef struct valores valores;

#define CALCULADORA_PROG 0x31111111
#define CALCULADORA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  float * suma_1(valores *, CLIENT *);
extern  float * suma_1_svc(valores *, struct svc_req *);
#define RESTA 2
extern  float * resta_1(valores *, CLIENT *);
extern  float * resta_1_svc(valores *, struct svc_req *);
#define MULTIPLICACION 3
extern  float * multiplicacion_1(valores *, CLIENT *);
extern  float * multiplicacion_1_svc(valores *, struct svc_req *);
#define DIVISION 4
extern  float * division_1(valores *, CLIENT *);
extern  float * division_1_svc(valores *, struct svc_req *);
extern int calculadora_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define RESTA 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define MULTIPLICACION 3
extern  float * multiplicacion_1();
extern  float * multiplicacion_1_svc();
#define DIVISION 4
extern  float * division_1();
extern  float * division_1_svc();
extern int calculadora_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_valores (XDR *, valores*);

#else /* K&R C */
extern bool_t xdr_valores ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
